version: '3.1'

services:

  mysql:
    container_name: oforgemysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    build: mysql/.
    deploy:
      resources:
        limits:
          memory: 1024M
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  adminer:
    image: adminer
    container_name: oforgeadminer
    restart: always
    ports:
      - 8080:8080
